#send_blocked block item from /emojis list
font_images:
  grid_menu_1:
    path: "gui/grid_menu_1.png"
    size: 170
    offset: 43 
    chars: "\\u3400"
    send_blocked: true
  grid_menu_2:
    path: "gui/grid_menu_2.png"
    size: 170
    offset: 43 
    chars: "\\u3401"
    send_blocked: true
  grid_menu_3:
    path: "gui/grid_menu_3.png"
    size: 170
    offset: 43 
    chars: "\\u3402"
    send_blocked: true
  grid_menu_4:
    path: "gui/grid_menu_4.png"
    size: 170
    offset: 43 
    chars: "\\u3403"
    send_blocked: true
  grid_menu_5:
    path: "gui/grid_menu_5.png"
    size: 170
    offset: 43
    chars: "\\u3404"
    send_blocked: true
  grid_menu_6:
    path: "gui/grid_menu_6.png"
    size: 170
    offset: 43
    chars: "\\u3405"
    send_blocked: true
  blank_menu:
    path: "gui/blank.png"
    size: 170
    offset: 43
    chars: "\\u3406"
    send_blocked: true

  crisps: 
    namespace: "empireemojis"
    path: "font/emoji/crisps.png"
    chars: "\\u3407"

#DO NOT DELETE THIS SECTION
offsets:
 l_1: "\uF801"
 l_2: "\uF802"
 l_3: "\uF803"
 l_4: "\uF804"
 l_5: "\uF805"
 l_6: "\uF806"
 l_7: "\uF807"
 l_8: "\uF808"
 l_16: "\uF809"
 l_32: "\uF80A"
 l_64: "\uF80B"
 l_128: "\uF80C"
 l_512: "\uF80D"
 l_1024: "\uF80E"
 r_1: "\uF821"
 r_2: "\uF822"
 r_3: "\uF823"
 r_4: "\uF824"
 r_5: "\uF825"
 r_6: "\uF826"
 r_7: "\uF827"
 r_8: "\uF828"
 r_16: "\uF829"
 r_32: "\uF82A"
 r_64: "\uF82B"
 r_128: "\uF82C"
 r_512: "\uF82D"
 r_1024: "\uF82E"    