settings:
  workbench_ui: "&f:l_16::grid_menu_6::l_128:"
  categories_text: "&f:l_16::grid_menu_6::l_128:#11d417Категории "
  drop_btn: more
  next_btn: next_button
  prev_btn: prev_button
  back_btn: back
  close_btn: cancel
  give_btn: ender_chest_opened

categories:
  upgrades:
    title: "&f:l_16::grid_menu_6::l_128:#9a11d4Апгрейды"
    name: "&2Апгрейды"
    icon: ender_scrap
    lore:
      - "&7Здесь показаны предметы"
      - "&7которыми можно улучшать экипировку"
    permission: emp.categories.upgrades
    items:
      - "ender_scrap"
