random_items:
  - attributes:
      - amount_max: 8
        amount_min: 7
        chance: 90
        name: GENERIC_ATTACK_DAMAGE
    custom_model_datas:
      - 1
      - 2
      - 3
      - 4
    display_names:
      - Меч ярости
      - Меч величия
    durability:
      max: 1200
      min: 1000
    enchantements:
      - amount_max: 4
        amount_min: 1
        chance: 90
        name: protection
    id: item_1
    item_flags:
      - HIDE_ATTRIBUTES
    lores:
      - - Наполняет владельца силой
        - Светится
      - - Наполняет жаждой убийства
        - Горит
    material: NETHERITE_SWORD