PLUGIN_PREFIX: "#18dbd1[EmpireItems]"
RELOAD: "#dbbb18Перезагрузка плагина"
RELOAD_COMPLETE: "#42f596Перезагрузка успешно завершена"
SAVE_ERROR: "#db2c18Не удалось сохранить файл"
NONSTANDART_FILE: "#db2c18Нестнадартный файл"
LOADING_FILE: "#18dbd1Загрузка файла"
NOT_EXIST_FILE: "#db2c18Файл не существует"
ITEM_GAINED: "#18dbd1Вы получили"
ITEM_GIVE: "#18dbd1Вы выдали"
ITEM_NOT_FOUND: "#db2c18Нет предмета"
WRONG_NUMBER: "#db2c18Количество задано неверно"
ITEM_REPLACED: "#18db52Предмет заменён"
ITEM_REPLACE_WRONG: "#db2f18Предмет не подходит для замены"
ZIP_SUCCESS: "#42f596Успешно завершено"
ZIP_ERROR: "#f55442Ошибка при упакове ресурс-пака"
RESOURCE_PACK_DENY: "#f55442Вы отклонили ресурс-пак"
RESOURCE_PACK_HINT_TITLE: "#db2518Скачайте ресурс-пак"
RESOURCE_PACK_HINT_SUBTITLE: "#18db4fВведите #189adb/empack. #18db4fОн нужен для новых предметов, звуков, оружие, брони и новых меню в #189adb/menu"
RESOURCE_PACK_DOWNLOAD_SELF: "#f54542Попробуйте скачать самостоятельно. #429ef5empireprojekt.ru/files/EmpireProjektPack.zip"
RESOURCE_PACK_DOWNLOAD_ERROR: "\n
    #f54542Не удалось загрузить ресурс-пак\n
    #f54542Скачайте его сами с #429ef5empireprojekt.ru/files/EmpireProjektPack.zip\n
    #f54542Дискорд #429ef5EmpireProjekt.ru/discord\n
    #f54542Группа ВК #429ef5EmpireProjekt.ru.vk"
FIRST_PAGE: "#f5a742Вы на первой странице"
LAST_PAGE: "#f5a742Вы на последней странице"
ITEM_UPGRADE_NAME_COLOR: "#4790ad"
ITEM_UPGRADE_AMOUNT_COLOR: "#47ad5f"
ITEM_INFO_IMPROVING: "Улучшает"
ITEM_INFO_IMPROVING_COLOR: "#47ad5f"
ITEM_INFO_DROP: "Выпадает из"
ITEM_INFO_DROP_COLOR: "#47ad5f"