ender_scrap:
  1:
    attr: GENERIC_ATTACK_DAMAGE
    add_min: 10.0
    add_max: 100.8
    slot: HAND
    type: [SWORD]
  2:
    attr: GENERIC_MAX_HEALTH
    add_min: 10.0
    add_max: 100.8
    slot: [CHEST]
    type: [CHESTPLATE]
  3:
    attr: GENERIC_MAX_HEALTH
    add_min: 10.0
    add_max: 100.8
    slot: [LEGS]
    type: [LEGGINGS]
  4:
    attr: GENERIC_MAX_HEALTH
    add_min: 10.0
    add_max: 100.8
    slot: [OFF_HAND,HAND]
    type: [SHIELD]