loot:
  blocks:
    MUSHROOM_STEM:
      ender_scrap:
        item: ender_scrap
        min_amount: 1
        max_amount: 1
        chance: 100
  mobs:
    ENDER_DRAGON:
      ender_scrap:
        item: ender_scrap
        min_amount: 1
        max_amount: 5
        chance: 100