settings:
  workbenchText: "&f:l_16::workbench_menu::l_128::l_32::l_4:"
  categoriesText: "&f:l_16::grid_menu_6::l_128::l_32::l_4:#1bbce0Категории "
  soundsText: "&f:l_16::grid_menu_6::l_128:#11d417Звуки "
  moreButton: more
  nextButton: next_button
  prevButton: prev_button
  backButton: back
  closeButton: cancel
  giveButton: ender_chest_opened
  furnaceButton: furnace
  craftingTableButton: crafting_table

  workbenchSound: empire_items:gui.next_page
  categoriesSound: empire_items:gui.open_menu
  categorySound: empire_items:gui.open_menu

categories:
  items:
    title: "&f:l_16::grid_menu_6::l_128::l_32::l_4:#e02b1bОбычные предметы"
    name: "#e02b1bОбычные предметы"
    icon: slime_bottle_active
    lore:
      - "&7Обычные и не очень предметы"
      - "&7Можно как найти в мире, так и скрафтить"
    items:
      - "bottle_for_slime"
      - "slime_bottle_active"
      - "co_inspect_lens"