resourcePack:
  link: "https://empireprojekt.ru/files/EmpireProjektPack_1.zip"
  requestOnJoin: true
  kickOnDeny: false
  requestDelay: 0
generation:
  # Дебаг генерации
  debug: true
  # Включена ли генерация блоков
  generate: true
  # Генерировать ли блоки только на новых чанках
  onlyOnNewChunks: false
  # Максимальный анализ этого количества чанков при их загрузке
  # То есть если одновременно загрузится 10 чанков - проанализированы будут только 5
  # 0 для отключения
  generateChunksAtOnce: 8
tabPrefix: "%vault_prefix%"