resourcePack:
  link: "https://empireprojekt.ru/files/EmpireProjektPack_1.zip"
  requestOnJoin: true
  kickOnDeny: false
empireEnchants:
  vampirismMultiplier: 0.05
blockGeneration:
  # Дебаг генерации
  debug: true
  # Включена ли генерация блоков
  generate: true
  # Генерировать ли блоки только на новых чанках
  onlyOnNewChunks: false
  # По достижению этого размера в очереди - будет вызвана очистка очереди
  # Максимлаьный размер не гарантирует того, что количество очередей не будет больше этого числа, а лишь даёт возможность предотвратить это
  maxQueueSize: 5000
  generationClearCheck: 10000
  # Когда чанк анализируется - блоки передаются в очередь, которая со временем чистится, если вблизи этой локации нет игроков
  # Это нужно для слабых серверов, на которых не хватает мощности чтобы сразу сгенерировать все блоки
  # Если установить на 0 - очереди не будет, а все блоки будут генерироваться в процессе анализа
  generateBlocksGap: 0
  # Максимальный анализ этого количества чанков при их загрузке
  # То есть если одновременно загрузится 10 чанков - проанализированы будут только 5
  # 0 для отключения
  maxChunksAtOnce: 5
mechanics:
  # Когда игрок ломает блоки в одном и том же месте - они не будут выпатьа, если это место сохранено в памяти
  block_location_memory_size: 60
tabPrefix: "%vault_prefix%"