main: com.makeevrserg.empireprojekt.EmpirePlugin
name: EmpireItems
version: 3.0.1
author: RatushevRoman
api-version: 1.13
softdepend: [PlaceholderAPI,ProtocolLib,WorldGuard]
depend: []
commands:
  ereload:
  erating:
  emsplash:
  emreplace:
  emoji:
  erandomitem:
  emcredit:
  embank:
  emsounds:
  emp:
  emr:
  emgui:
  ezip:
  thirst:
  emojis:
  emnbt:
  emrepair:
  empack:
  emess:
  sit:
  emnpc:
  skin:
  eminv:
  emspawn:
  empireitems:
    usage: |
      /ereload - Перезагружает плагин
      /emp give - дает предмет
      /ezip - создает архив
